
import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { Prisma } from '@prisma/client';

// ... imports
import { AiService } from '../ai/ai.service';

@Injectable()
export class ExplanationService {
    private readonly logger = new Logger(ExplanationService.name);

    constructor(
        private readonly prisma: PrismaService,
        private readonly aiService: AiService
    ) { }

    async create(data: Prisma.ExplanationCreateInput) {
        return this.prisma.explanation.create({ data });
    }

    async generate(key: string, category: string, context?: string) {
        const generated = await this.aiService.generateExplanation(key, category, context);

        return this.upsertByKey(key, {
            key,
            category,
            title: generated.title,
            content: generated.content,
            examples: generated.examples,
            isAutoGenerated: true
        });
    }



    async findAll(category?: string) {
        const where: Prisma.ExplanationWhereInput = category ? { category } : {};
        return this.prisma.explanation.findMany({ where });
    }

    async findOne(id: string) {
        const explanation = await this.prisma.explanation.findUnique({ where: { id } });
        if (!explanation) {
            throw new NotFoundException(`Explanation with ID ${id} not found`);
        }
        return explanation;
    }

    async findByKey(key: string) {
        const explanation = await this.prisma.explanation.findUnique({ where: { key } });
        // If not found, we might want to return null so the frontend can handle it (or auto-generate)
        return explanation;
    }

    async update(id: string, data: Prisma.ExplanationUpdateInput) {
        return this.prisma.explanation.update({
            where: { id },
            data,
        });
    }

    // Upsert by key
    async upsertByKey(key: string, data: Prisma.ExplanationCreateInput) {
        return this.prisma.explanation.upsert({
            where: { key },
            create: data,
            update: {
                title: data.title,
                content: data.content,
                examples: data.examples,
                category: data.category
            }
        });
    }

    async remove(id: string) {
        return this.prisma.explanation.delete({ where: { id } });
    }
}
