
import { Injectable, Logger } from '@nestjs/common';
import { AiProviderManager } from '../../ai/provider/ai-provider.manager';

@Injectable()
export class RequirementGeneratorAgent {
  private readonly logger = new Logger(RequirementGeneratorAgent.name);

  constructor(private readonly aiManager: AiProviderManager) {}

  async execute(jobId: string, stepId: string, goalData: any, contextData: any, type: 'FUNC' | 'NFR' | 'SEC' = 'FUNC', desiredModel?: string) {
    const typeFull = type === 'FUNC' ? 'Functional' : type === 'NFR' ? 'Non-Functional' : 'Security';
    
    const prompt = `
      You are a Senior Requirement Architect.
      Generate 3 to 5 high-quality ${typeFull} requirements based on the Goal and Context.
      
      Goal: ${JSON.stringify(goalData)}
      Context: ${JSON.stringify(contextData)}
      
      Instructions:
      1. Return a JSON Object with a "requirements" array.
      2. Each requirement MUST have: "title", "content", "priority".
      3. **IMPORTANT**: All content (Title, Content, Rationale) MUST be written in **Korean** (한국어).
      
      Example Output:
      {
        "requirements": [
          {
            "category": "${type}",
            "title": "User Authentication",
            "content": "The system shall allow users to log in using Email and Password.",
            "rationale": "Standard security practice.",
            "priority": "HIGH"
          }
        ]
      }
    `;

    try {
        const res = await this.aiManager.execute({
            messages: [{ role: 'user', content: prompt }],
            responseFormat: 'json_object',
        }, 'GENERATION');
        
        // Clean JSON (remove markdown code blocks)
        const cleanContent = res.content.replace(/```json/g, '').replace(/```/g, '').trim();
        const json = JSON.parse(cleanContent);
        const result = json.requirements || json;
        const arr = Array.isArray(result) ? result : [result];
        // Validate and Fix Structure
        const validItems = arr.map((item: any) => {
            if (!item) return null;
            
            // Try to find content in various common fields
            let content = item.content || item.description || item.requirement || item.goal || item.text || item.summary || item.value;
            
            // If still empty, try to use rationale or title as content if they exist
            if (!content && item.rationale) content = `Rationale: ${item.rationale}`;
            if (!content && item.title) content = item.title;

            // Ensure content is string
            if (content && typeof content !== 'string') {
                content = JSON.stringify(content);
            }
            
            // Final fallback if truly nothing exists
            if (!content || content === '{}' || content === '[]') {
                content = 'Content not generated by AI.';
            }

            return {
                category: type,
                title: item.title || item.name || 'Generated Requirement',
                content: content,
                priority: item.priority || 'MEDIUM',
                rationale: item.rationale || 'Generated by AI'
            };
        }).filter(item => item !== null);
        
        if (validItems.length === 0) {
            // Last Resort Fallback: use Goal string
            const goalText = typeof goalData === 'string' ? goalData : (goalData.goal || JSON.stringify(goalData));
            return [{ 
                category: type, 
                title: 'Manual Review Required', 
                content: `AI output was invalid. Original Goal: ${goalText}`, 
                priority: 'HIGH' 
            }];
        }
        return validItems;
    } catch (e) {
        this.logger.error('Generation failed', e);
        return [
            { category: 'FUNC', title: 'Basic Requirement', content: 'System must function according to goal.', rationale: 'Fallback', priority: 'HIGH' }
        ];
    }
  }
}
